services:
  # Backend API Service
  - type: web
    name: favbooks-backend
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false

  # Frontend Service
  - type: web
    name: favbooks-frontend
    env: static
    plan: free
    branch: master
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false

  # PostgreSQL Database
  - type: pserv
    name: favbooks-db
    region: oregon
    plan: free
    branch: master

